experimentName: DRIVE
searchSpaceFile: search_space.json
trialCommand: python train.py -d "Kvasir-SEG" -m "PMFSNet" -dim "2d" -s "BASIC"
trialCodeDirectory: ./  # 确保代码目录正确
trialGpuNumber: 1
experimentWorkingDirectory: ./log
logLevel: info
trialConcurrency: 6  # 并发运行的最大试验数（根据你 GPU 数量调整）

# 配置调参器使用的 GPU
tunerGpuIndices: [0, 1, 2, 3]

# 最大实验时长
maxExperimentDuration: 2d
maxTrialNumber: 200

tuner:
  name: TPE
  classArgs:
    optimize_mode: maximize

trainingService:
  platform: local
  gpuIndices: [0, 1, 2, 3]  # 可用的 GPU
  maxTrialNumberPerGpu: 1 # 每个 GPU 上最多允许的并发试验数
  useActiveGpu: True